### PR TITLE
Added the Steering Committee to the people page.

### PR DESCRIPTION
**Pull request by stuckyb**
Added a section for the steering committee, along with a few minor edits
on the rest of the page.

### CODE REVIEW

**Comment by eightysteele** [comment]
LGTM. #shipit

**Comment by jmalczyk** [comment]
What? No comment about those super long lines? 80 characters please!

**Comment by stuckyb** [comment]
I made the lines shorter, but some of the lines still exceed 80 characters.  Many other lines in the file already greatly exceed 80 chars, so I assume that is okay.

**Comment by tomauer** [comment]
I never warned Brian and we totally hadn't been sticking to 80 char width for static HTML pages.

**Comment by eightysteele** [comment]
Good cop bad cop fellas, good cop bad cop. Also, I think we should all be on the steering committee ha.

**Pull request merged**
