### PR TITLE
All New Layer Styling

### PR DESCRIPTION
**Pull request by tomauer**
Sorry that this is such a beast, it's had a lot of things tacked onto it and I finally drew the line and Jeremy and I got it operational. I will make an effort to break these sorts of things up more in the future.

Check it out here: http://tom-auer.appspot.com/

MOST IMPORTANT. If this doesn't merge automatically, which I doubt it will, instead of hard copying the changes over, let me merge this into develop on my local, resolve merge conflicts there, and then push straight to develop, that way we won't lose anything. There was a problem with this last time.

### CODE REVIEW

**Comment by eightysteele** [comment]
BEAST MODE! Looking good dude. I think you'll need a rebase on develop before this can be merged in.

Couple of things: If you click 'style all' and then 'remove all', the style all window doesn't go away and the loading GIF keeps spinning.

**Comment by tomauer** [comment]
Good catch. Unfortunately the fix is proving hard to catch.

**Comment by eightysteele** [comment]
Ha yeah, probably super subtle.

**Comment by tomauer** [comment]
If you start removing layers, the widget control doesn't resize. I need to fix that before this can go.

**Comment by tomauer** [comment]
Actually, the widget control resizing thing is a separate bug, so this doesn't need to wait for that.

**Comment by tomauer** [comment]
I'm closing this one and will submit a new one in a little while that has been rebased and will merge automatically, which is awesome.

**Pull request closed without merging**
